#! /bin/sh
echo "start..."


# h1->s4
ovs-ofctl add-flow s4 in_port=4,actions=output:flood

# s1,s2,s3
ovs-ofctl add-flow s1 in_port=1,actions=output:2
ovs-ofctl add-flow s2 in_port=1,actions=output:2
ovs-ofctl add-flow s3 in_port=1,actions=output:2

# s5
ovs-ofctl add-flow s5 in_port=1,actions=output:4
ovs-ofctl add-flow s5 in_port=2,actions=output:4
ovs-ofctl add-flow s5 in_port=3,actions=output:4

chmod 777 ovs-5-sw

